### ISSUE TITLE
abort due apt-get install "additional disk space ... continue?" question

### ISSUE THREAD

**Issue by DessertHunter** [SandraK82/deploy-ns-local-raspi#1]
On my Raspberry first Generation with RASPBIAN JESSIE LITE Version 4.4/2016-09-23 apt-get install is asking because of "additional disk space will be used. Do you want to continue? [Y/n]" question.

I think the first problematic line is 15: `sudo apt-get install npm`
I think  apt-get install _xyz_ **--assume-yes** in every `sudo apt-get install` line without `-y` (eg. `sudo apt-get install mongodb-server`) should do the fix. [see](http://superuser.com/questions/287348/why-does-apt-get-sometimes-asks-for-confirmation)

Full console log see attachement.
[abort due apt-get install question.txt](https://github.com/SandraK82/deploy-ns-local-raspi/files/512203/abort.due.apt-get.install.question.txt)

**Comment by SandraK82** [comment]
Yes, you have to say Y for the install commands, i could change it to silent mode, however i wanted to give the user the ability to see and unterstand what is happening during Installation.
The package installer asks if it is allowed to use diskspace to install the needed tools.

**Comment by SandraK82** [comment]
resolved with PR from @DessertHunter
